<?xml version="1.0"?>
<robot name="lino" xmlns:xacro="http://ros.org/wiki/xacro">

<!--    mass and inertia-->
    <xacro:property name="PI_2" value="1.57079632679" />
    <xacro:property name="base_link_m" value="1" />
    <xacro:property name="r_wheel_m" value="0.5" />
    <xacro:property name="l_wheel_m" value="0.5" />
    <xacro:property name="front_castor_m" value="0.1" />
    <xacro:property name="rear_castor_m" value="0.1" />

<!--    dimensions-->
    <xacro:property name="base_link_h" value="0.1235" />
    <xacro:property name="base_link_l" value="0.7" />
    <xacro:property name="base_link_w" value="0.45" />
    <xacro:property name="wheels_from_ground" value="0.02" />
    <xacro:property name="wheels_d" value="0.125" />
    <xacro:property name="wheels_w" value="0.06" />
	<xacro:property name="wheels_center_shift_base_link" value="${(wheels_d/2)-wheels_from_ground }" />
    <xacro:property name="dist_bet_wheels" value="0.1575" />
    <xacro:property name="dist_bet_castors" value="0.25" />
    <xacro:property name="laser_r" value="0.03" />
    <xacro:property name="laser_l" value="0.05" />
    <xacro:property name="laser_x" value="${0.625 - (base_link_l/2)}" />
    <xacro:property name="laser_z" value="${base_link_h+(laser_l/2)}" />

<!--    laser data-->
    <xacro:property name="laser_angular_res" value="${1}" />
    <xacro:property name="laser_angle" value="${(270/180)*(PI_2*2)}" />
    <xacro:property name="laser_min_range" value="${0.1}" />
    <xacro:property name="laser_max_range" value="${10}" />
    <xacro:property name="laser_linear_res" value="${0.001}" />

<!--    materials-->
    <material name="yellow">
       <color rgba="1.0 1.0 0.1 1.0"/>
    </material>
    <material name="white">
       <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="black">
       <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="blue">
       <color rgba="0.0 0.0 1.0 1.0"/>
    </material>

<!--    transmission block-->
    <xacro:macro name="transmission_block" params="joint_name">
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
               <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <mechanicalReduction>1</mechanicalReduction>
                <hardwareInterface>hardware_interface/PositionInterface</hardwareInterface>
            </actuator>
        </transmission>
    </xacro:macro>

<!--    link list-->
    <link name="base_footprint"/>
    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <link name="base_link">
        <inertial>
            <mass value="${base_link_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03"/>
        </inertial>
        <visual>
            <geometry>
                <mesh filename="package://lino_description/meshes/base_link.stl"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lino_description/meshes/base_link.stl"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <turnGravityOff>false</turnGravityOff>
        <material>Gazebo/White</material>
    </gazebo>

    <link name="r_wheel">
        <inertial>
            <mass value="${r_wheel_m}"/>
            <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
            <inertia ixx="0.015" ixy="0" ixz="0" iyy="0.015" iyz="0" izz="0.015"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
            <geometry>
                <cylinder radius="${wheels_d/2}" length="${wheels_w}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
            <geometry>
                <cylinder radius="${wheels_d/2}" length="${wheels_w}"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="r_wheel">
        <mu1 value="2.0"/>
        <mu2 value="2.0"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <material>Gazebo/Black</material>
    </gazebo>

    <link name="l_wheel">
        <inertial>
            <mass value="${l_wheel_m}"/>
            <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
            <inertia ixx="0.015" ixy="0" ixz="0" iyy="0.015" iyz="0" izz="0.015"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
            <geometry>
                <cylinder radius="${wheels_d/2}" length="${wheels_w}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
            <geometry>
                <cylinder radius="${wheels_d/2}" length="${wheels_w}"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="l_wheel">
        <mu1 value="2.0"/>
        <mu2 value="2.0"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <material>Gazebo/Black</material>
    </gazebo>

    <link name="front_castor">
        <inertial>
            <mass value="${front_castor_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.003"/>
        </inertial>
        <visual>
            <geometry>
                <mesh filename="package://lino_description/meshes/castor_wheel.stl"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lino_description/meshes/castor_wheel.stl"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_castor">
        <turnGravityOff>false</turnGravityOff>
        <material>Gazebo/Yellow</material>
    </gazebo>

    <link name="rear_castor">
        <inertial>
            <mass value="${rear_castor_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.003"/>
        </inertial>
        <visual>
            <geometry>
                <mesh filename="package://lino_description/meshes/castor_wheel.stl"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lino_description/meshes/castor_wheel.stl"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="rear_castor">
        <turnGravityOff>false</turnGravityOff>
        <material>Gazebo/Yellow</material>
    </gazebo>

    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="${laser_r}" length="${laser_l}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <gazebo reference="laser_link">
        <turnGravityOff>false</turnGravityOff>
        <material>Gazebo/Blue</material>
        <sensor type="ray" name="laser">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>${laser_angular_res}</resolution>
                        <min_angle>${-laser_angle/2}</min_angle>
                        <max_angle>${laser_angle/2}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${laser_min_range}</min>
                    <max>${laser_max_range}</max>
                    <resolution>${laser_linear_res}</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

<!--        joint list-->
    <joint name="base_footprint_base_link" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 ${wheels_from_ground}"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>
    <joint name="base_link_front_castor" type="fixed">
        <origin rpy="0 0 0" xyz="${dist_bet_castors} 0 ${-wheels_from_ground}"/>
        <parent link="base_link"/>
        <child link="front_castor"/>
    </joint>

    <joint name="base_link_rear_castor" type="fixed">
        <origin rpy="0 0 0" xyz="${-dist_bet_castors} 0 ${-wheels_from_ground}"/>
        <parent link="base_link"/>
        <child link="rear_castor"/>
    </joint>

    <joint name="base_link_laser" type="fixed">
        <origin rpy="0 0 0" xyz="${laser_x} 0 ${laser_z}"/>
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <joint name="r_wheel_joint" type="continuous">
        <origin rpy="0 0 0" xyz="0 ${dist_bet_wheels} ${(wheels_d/2)- (wheels_from_ground)}"/>
        <parent link="base_link"/>
        <child link="r_wheel"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort="100" velocity="100"/>
    </joint>
<!--    <xacro:transmission_block joint_name="r_wheel_joint"/>-->

    <joint name="l_wheel_joint" type="continuous">
        <origin rpy="0 0 0" xyz="0 ${-dist_bet_wheels} ${(wheels_d/2)- (wheels_from_ground)}"/>
        <parent link="base_link"/>
        <child link="l_wheel"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort="100" velocity="100"/>
    </joint>
<!--    <xacro:transmission_block joint_name="l_wheel_joint"/>-->
  <!-- Gazebo plugin for ROS Control -->
    <gazebo>
  <!-- Differential drive controller  -->
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <legacyMode>true</legacyMode>
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <publishOdomTF>true</publishOdomTF>
            <robotNamespace>/</robotNamespace>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <leftJoint>l_wheel_joint</leftJoint>
            <rightJoint>r_wheel_joint</rightJoint>
            <wheelSeparation>${dist_bet_wheels}</wheelSeparation>
            <wheelDiameter>${wheels_d}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>10</wheelTorque>
            <wheelAcceleration>2</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryTopic>odom</odometryTopic>
            <odometrySource>world</odometrySource>
            <publishTf>1</publishTf>
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>
</robot>